### PR TITLE
Added constructor overload to outsource authentication

### PR DESCRIPTION
**Pull request by JonasSyrstad**
Added constructor overload to outsource authentication to external code. and added some validation of the input parameters in the constructors

### CODE REVIEW

**Comment by JonasSyrstad** [comment]
Have refactored the auth to return a class.
However, if the developer is using a library like ADAL there is no problem outsorcing the whole thing to the external code.
I have also made the HttpClient a static (it is recommended in MS documentation to have only one instance)

**Comment by nianton** [comment]
Thank you Jonas, we are mostly good, I will probably do some minor changes to save us some time and I will merge the changes to the master tomorrow. Yes, you are right about the ADAL library since it caches internally the access token, the callback though does not indicate such behavior.

**Comment by nianton** [comment]
Thanks Jonas -it will be released as v1.3.0 later in the day.

**Comment by JonasSyrstad** [comment]
awsome, thanks for your good work

**Pull request merged**
